# Test simple de impresion
print("===============================================")
print("TEST DE IMPRESION - Panel de Control")
print("===============================================")
print("")
print("Si puedes ver esto, Python funciona!")
print("")
print("Probando caracteres:")
print("[+] Check positivo")
print("[-] Check negativo")
print("[!] Advertencia")
print("[i] Informacion")
print("[OK] Todo bien")
print("")
print("===============================================")
print("Test completado exitosamente")
print("===============================================")

input("\nPresiona ENTER para salir...")
