-- Reporte de Viajes Completos por Rango de Fechas
-- Obtiene todos los datos de la tabla viajes filtrados por fecha
-- Parámetros: fecha_inicio, fecha_fin
-- Formato esperado: 'YYYY-MM-DD'

SELECT 
    numero_viaje,
    casino,
    ruta,
    tipo_camion,
    patente_camion,
    patente_semi,
    numero_rampa,
    peso_camion,
    costo_codigo,
    termografos_gps,
    fecha,
    fecha_hora_llegada_dhl,
    fecha_hora_salida_dhl,
    conductor,
    celular,
    rut,
    numero_camion,
    num_wencos,
    bin,
    pallets,
    pallets_chep,
    pallets_pl_negro_grueso,
    pallets_pl_negro_alternativo,
    pallets_refrigerado,
    wencos_refrigerado,
    pallets_congelado,
    wencos_congelado,
    pallets_abarrote,
    check_congelado,
    check_refrigerado,
    check_abarrote,
    check_implementos,
    check_aseo,
    check_trazabilidad,
    check_plataforma_wtck,
    check_env_correo_wtck,
    check_revision_planilla_despacho,
    sello_salida_1p,
    sello_salida_2p,
    sello_salida_3p,
    sello_salida_4p,
    sello_salida_5p,
    sello_retorno_1p,
    sello_retorno_2p,
    sello_retorno_3p,
    sello_retorno_4p,
    sello_retorno_5p,
    guia_1,
    guia_2,
    guia_3,
    guia_4,
    guia_5,
    guia_6,
    guia_7,
    guia_8,
    guia_9,
    guia_10,
    guia_11,
    guia_12,
    guia_13,
    guia_14,
    numero_certificado_fumigacion,
    revision_limpieza_camion_acciones,
    administrativo_responsable
FROM viajes
WHERE fecha BETWEEN ? AND ?
ORDER BY fecha, numero_viaje
